iter13
ivas1ly/uwu-metrics pull request #13
Opened 2023-12-12 09:34 UTC by ivas1ly

2023-12-13 16:55 UTC, arttet requested changes

2023-12-13 16:55 UTC, arttet commented on db/embed.go
It would be better if you rename it like `migrations`

2023-12-13 16:55 UTC, arttet commented on internal/agent/client.go
> +	retryIntervals = []time.Duration{1 * time.Second, 3 * time.Second, 5 * time.Second}
Please use https://pkg.go.dev/github.com/cenkalti/backoff/v4#section-readme

2023-12-13 16:55 UTC, arttet commented on internal/lib/migrate/migrate.go
Why do you name it as `lib`?

2023-12-13 16:55 UTC, arttet commented on internal/lib/postgres/database.go
> +	withTimeout, cancel := context.WithTimeout(ctx, connTimeout)
You don't need to do it. You can provide a context with timeout.

2023-12-13 16:55 UTC, arttet commented on internal/server/server.go
> +	var db *postgres.DB
Please split routes and their implementation. It would be better if they are in another file like `route.go`

2023-12-13 16:55 UTC, arttet commented on internal/server/server.go
> +		log.Info("received connection string", zap.String("connString", cfg.DatabaseDSN))
It would be better if it is another function.

2023-12-13 16:55 UTC, arttet commented on internal/server/storage/persistent/database/db.go
> +	saveGauge = "INSERT INTO metrics (id, mtype, mdelta, mvalue) VALUES ($1, $2, $3, $4) ON CONFLICT (id) DO UPDATE SET mvalue = EXCLUDED.mvalue;"
What if we would like to use another database management system?

2023-12-13 16:55 UTC, arttet commented on internal/server/storage/persistent/database/db.go
> +	db            *postgres.DB
Why we should have two instances?

2023-12-13 16:55 UTC, arttet commented on internal/server/storage/persistent/database/db.go
> +	ctx := context.Background()
You need to provide a context here.

2023-12-17 18:40 UTC, ivas1ly commented on codecov.yml
> +    patch: off
https://docs.codecov.com/docs/commit-status#patch-status

2023-12-18 16:21 UTC, arttet requested changes

2023-12-18 16:21 UTC, arttet commented on db/migrations/000001_init.up.sql
> +    PRIMARY KEY (id)
Would you like to add any constraint?

2023-12-18 16:21 UTC, arttet commented on internal/server/route.go
> +	router.Use(middleware.Compress(defaultCompressLevel))
It would be better if you use one style.

2023-12-18 16:21 UTC, arttet commented on internal/server/route.go
> +			log.Info("database connection string is empty, nothing to ping")
It should be an error

2023-12-18 16:21 UTC, arttet commented on internal/server/route.go
> +func pingDB(ctx context.Context, log *zap.Logger, db *postgres.DB) http.HandlerFunc {
This context should be from the request.

2023-12-18 16:21 UTC, arttet commented on internal/server/route.go
> +func pingDB(ctx context.Context, log *zap.Logger, db *postgres.DB) http.HandlerFunc {
Usually, `logger` is the latest parameter.

2023-12-18 16:21 UTC, arttet commented on internal/server/server.go
> +func SetupPersistentStorage(ctx context.Context, log *zap.Logger, cfg *Config,
Could you please simplify this function?

2023-12-18 16:21 UTC, arttet commented on internal/server/storage/persistent/database/db.go
> +	saveGauge = "INSERT INTO metrics (id, mtype, mdelta, mvalue) VALUES ($1, $2, $3, $4) ON CONFLICT (id) DO UPDATE SET mvalue = EXCLUDED.mvalue;"
What if we would like to use another database management system?

2023-12-18 16:21 UTC, arttet commented on internal/server/storage/persistent/database/db.go
> +	getMetrics  = "SELECT id, mtype, mdelta, mvalue FROM metrics;"
Should we use any constraint?

2023-12-18 16:21 UTC, arttet commented on internal/server/storage/persistent/database/db.go
> +	db            *postgres.DB
Why we should have two instances?

2023-12-20 11:36 UTC, ivas1ly commented on internal/server/storage/persistent/database/db.go
> +	db            *postgres.DB
> Why we should have two instances?

According to the task, it is specified to temporarily store metrics somewhere before saving them in persistent storage.

2023-12-20 11:40 UTC, ivas1ly commented on internal/server/storage/persistent/database/db.go
> +	saveGauge = "INSERT INTO metrics (id, mtype, mdelta, mvalue) VALUES ($1, $2, $3, $4) ON CONFLICT (id) DO UPDATE SET mvalue = EXCLUDED.mvalue;"
According to the task, only postgres is supposed to be used.

2023-12-20 20:46 UTC, ivas1ly commented on internal/server/route.go
> +	router.Use(middleware.Compress(defaultCompressLevel))
There is a conflict here with another package name (`"github.com/go-chi/chi/v5/middleware"`), can't use one style.

2023-12-20 20:58 UTC, ivas1ly commented on internal/agent/client.go
> +	retryIntervals = []time.Duration{1 * time.Second, 3 * time.Second, 5 * time.Second}
Adding a library if the problem is solved with two lines is overengineering.

2023-12-21 07:55 UTC, arttet requested changes

2023-12-21 07:55 UTC, arttet commented on internal/lib/postgres/database.go
> +func retryWithAttempts(fn func() error, connAttempts int, connTimeout time.Duration) error {
https://pkg.go.dev/github.com/cenkalti/backoff/v4

2023-12-21 07:55 UTC, arttet commented on internal/lib/postgres/database.go
> +type DB struct {
Are you sure that you need it?

2023-12-21 07:55 UTC, arttet commented on internal/server/route.go
> +func pingDB(db *postgres.DB, log *zap.Logger) http.HandlerFunc {
Please move it to handlers or middlewares

2023-12-21 07:55 UTC, arttet commented on internal/server/server.go
> +//nolint:whitespace //necessary leading newline
Why?

2023-12-21 07:55 UTC, arttet commented on internal/server/server.go
> +		log.Panic("can't ping database", zap.Error(err))
Please don't panic here. It would be better if you return an error.

2023-12-21 07:55 UTC, arttet commented on internal/server/storage/persistent/database/db.go
> +	//nolint:lll // const query
What is it?

2023-12-21 07:55 UTC, arttet commented on internal/server/storage/persistent/database/db.go
> +	withTimeout, cancel := context.WithTimeout(ctx, ds.timeout)
Why do you need to do it here?

2023-12-21 07:55 UTC, arttet commented on migrations/000001_init.up.sql
> +CREATE INDEX IF NOT EXISTS metrics_id_idx ON metrics (id);
What type of index do you use?
How many indexes do you have?

2023-12-21 11:56 UTC, ivas1ly commented on internal/lib/postgres/database.go
> +type DB struct {
Yes I am sure

2023-12-21 12:02 UTC, ivas1ly commented on internal/lib/postgres/database.go
> +func retryWithAttempts(fn func() error, connAttempts int, connTimeout time.Duration) error {
This library is not needed here, the problem can be solved without unnecessary dependencies. Besides, I wanted to solve the problem on my own. It could be used for another project where it is really needed.

2023-12-21 12:19 UTC, ivas1ly commented on internal/server/route.go
> +func pingDB(db *postgres.DB, log *zap.Logger) http.HandlerFunc {
OK

2023-12-21 12:20 UTC, ivas1ly commented on internal/server/server.go
> +		log.Panic("can't ping database", zap.Error(err))
OK, now the error returns here

2023-12-21 12:21 UTC, ivas1ly commented on internal/server/server.go
> +//nolint:whitespace //necessary leading newline
A strange and unclear question. Added a more detailed comment here.

2023-12-21 12:37 UTC, ivas1ly commented on internal/server/storage/persistent/database/db.go
> +	withTimeout, cancel := context.WithTimeout(ctx, ds.timeout)
Yes, not needed here, fixed it.

2023-12-21 12:38 UTC, ivas1ly commented on internal/server/storage/persistent/database/db.go
> +	//nolint:lll // const query
String length linter, changed the string type to multiline.

2023-12-21 12:43 UTC, ivas1ly commented on migrations/000001_init.up.sql
> +CREATE INDEX IF NOT EXISTS metrics_id_idx ON metrics (id);
A single b-tree index is used for the primary key.

2023-12-21 17:24 UTC, arttet approved these changes

2023-12-23 13:46 UTC, merged