Iter5
ivas1ly/uwu-metrics pull request #5
Opened 2023-11-05 17:29 UTC by ivas1ly

2023-11-07 14:47 UTC, arttet requested changes
Please add linters in CI https://github.com/golangci/golangci-lint
Please add the code coverage report in CI https://about.codecov.io/blog/getting-started-with-code-coverage-for-golang/
Please add gofmt in CI https://github.com/marketplace/actions/check-code-formatting-using-gofmt

2023-11-07 14:47 UTC, arttet commented on Makefile
> +clean:
```suggestion
.PHONY: clean
clean:
```
https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html

2023-11-07 14:47 UTC, arttet commented on Makefile
> +iter3: iter2
Please avoid duplicate code

2023-11-07 14:47 UTC, arttet commented on README.md
> +# uwu-metrics
What does it mean?

2023-11-07 14:47 UTC, arttet commented on internal/agent/agent.go
> +		Level: slog.LevelDebug,
What if we want to override it?

2023-11-07 14:47 UTC, arttet commented on internal/agent/agent.go
> +type Gauge float64
It seems it should be another file

2023-11-07 14:47 UTC, arttet commented on internal/agent/agent.go
> +	for {
We should be able to stop this loop

2023-11-07 14:47 UTC, arttet commented on internal/agent/agent.go
> +	runtime.ReadMemStats(&ms.MemStats)
What if we get an error?

2023-11-07 14:47 UTC, arttet commented on internal/agent/agent.go
> +	return min + rand.Float64()*(max-min)
https://stackoverflow.com/questions/23577091/generating-random-numbers-over-a-range-in-go

2023-11-07 14:47 UTC, arttet commented on internal/agent/agent.go
> +func randFloat(min, max float64) float64 {
It should be in the utils package

2023-11-07 14:47 UTC, arttet commented on internal/agent/agent.go
> +	metrics := Metrics{}
```suggestion
	metrics := &Metrics{}
```

2023-11-07 14:47 UTC, arttet commented on internal/agent/client.go
> +	resp, err := http.DefaultClient.Do(req)
Should we care about timeouts?

2023-11-07 14:47 UTC, arttet commented on internal/agent/config.go
> +	ri := flag.Int("r", defaultReportInterval, "frequency of sending metrics "+
Please use `format` for strings

2023-11-07 14:47 UTC, arttet commented on internal/handlers/metrics.go
> +func (h *MetricsHandler) NewMetricsRoutes(router *chi.Mux) {
```suggestion
func (h *MetricsHandler) NewRoutes(router *chi.Mux) {
```

2023-11-07 14:47 UTC, arttet commented on internal/handlers/metrics.go
> +type MetricsHandler struct {
It should be a private struct

2023-11-07 14:47 UTC, arttet commented on internal/handlers/metrics.go
> +var content embed.FS
It should be at the top of this file.

2023-11-07 14:47 UTC, arttet commented on internal/handlers/templates/index.gohtml
Why not `index.html`?

2023-11-07 14:47 UTC, arttet commented on internal/handlers/templates/index.gohtml
It should be in `web/template`
https://github.com/golang-standards/project-layout/tree/master/web/template

2023-11-07 14:47 UTC, arttet commented on internal/metrics/metrics.go
It looks like `model`

2023-11-07 14:47 UTC, arttet commented on internal/storage/storage.go
> +type MemStorage struct {
It should be a private struct

2023-11-09 14:09 UTC, ivas1ly commented on internal/agent/agent.go
> +	runtime.ReadMemStats(&ms.MemStats)
> What if we get an error?

This function can't return an error (function signature - `func ReadMemStats(m *MemStats)`.

2023-11-09 15:16 UTC, ivas1ly commented on internal/agent/agent.go
> +	return min + rand.Float64()*(max-min)
> [stackoverflow.com/questions/23577091/generating-random-numbers-over-a-range-in-go](https://stackoverflow.com/questions/23577091/generating-random-numbers-over-a-range-in-go)

https://stackoverflow.com/questions/49746992/generate-random-float64-numbers-in-specific-range-using-golang

Here I need a float instead of an integer.

2023-11-12 16:09 UTC, arttet approved these changes

2023-11-16 16:00 UTC, merged